services:
  db:
    image: postgres:16
    container_name: inventory_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory_user -d inventory"]
      interval: 5s
      timeout: 5s
      retries: 5
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/root/task
    working_dir: /root/task
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    network_mode: bridge
